name: app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  google_maps_flutter: ^2.9.0
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1
  share_plus: ^10.1.3
  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  google_sign_in: 6.2.2
  cloud_firestore: ^6.1.2
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.5
  geocoding: ^4.0.0
  flutter_polyline_points: ^3.1.0
  http: ^1.6.0
  sensors_plus: ^6.1.1
  light_sensor: ^3.0.0
  get: ^4.7.3
  video_player: ^2.11.0
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/videos/
